<?php

namespace iahmPageBundle\Repository;

/**
 * ArticleHtmlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleHtmlRepository extends \Doctrine\ORM\EntityRepository
{
}
