iahm_page_homepage:
    path:     /
    defaults: { _controller: iahmPageBundle:Default:index }

iahm_page_donations:
    path:     /donations
    defaults: { _controller: iahmPageBundle:Default:donations }

iahm_page_thanks:
    path:     /thanks
    defaults: { _controller: iahmPageBundle:Default:thanks }

iahm_page_form:
    path:     /form/{id}
    defaults: { _controller: iahmPageBundle:Default:form }

iahm_page_header_nav:
    path:     /header_nav
    defaults: { _controller: iahmPageBundle:Default:headerNav }