iahm_page:
    resource: "@iahmPageBundle/Resources/config/routing.yml"

iahm_live:
    resource: "@iahmLiveBundle/Resources/config/routing.yml"

iahm_event:
    resource: "@iahmEventBundle/Resources/config/routing.yml"