iahm_default:
    resource: "@iahmLiveBundle/Resources/config/routing.yml"
    prefix:   /

iahm_live:
    resource: "@iahmLiveBundle/Resources/config/routing.yml"
    prefix:   /live

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
