<?php

namespace iahmEventBundle\Repository;

/**
 * BioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BioRepository extends \Doctrine\ORM\EntityRepository
{
}
