iahm_live_homepage:
    path:     /live
    defaults: { _controller: iahmLiveBundle:Default:index }

iahm_live_event:
    path:     /event/{id}
    defaults: { _controller: iahmLiveBundle:Default:event }
